= Histoire de la conteneurisation : chronologie
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:resourcesdir: ./resources
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

// toc::[]

== Version abrégée mais avec toutes les dates

* *1979* : développement de *chroot*, dans la version 7 d'Unix, Le concept d'isolation émerge. +
-> "le point de départ, les prémices de la conteneurisation"
* *2000/03* : *FreeBSD Jails* 
* *2001* : *Linux VServer*
* *2002/08* : Les 1er *Linux namespaces* (mount namespaces) sont ajoutés au kernel Linux 2.4.19 (2002/08/03)
* *2003* : Google introduced *Borg*, the organization's container cluster management system.
* *2004* : *Solaris Containers*
* *2005* : *Open VZ* (Open Virtuzzo)
* *2006* : début des travaux sur les *Process Containers* chez Google (later renamed *cgroups* / Control Groups)
* *2007/10* : ajout des 1eres briques de l'implémentation des *user namespaces* dans le kernel Linux 2.6.23 par Eric Biederman (Red Hat)
* *2008/01* : GRANDE ETAPE - ajout de la fonctionnalité des *cgroups* dans le kernel Linux 2.6.24
* *2008/08* : GRANDE ETAPE - création du projet *Linux Containers (LXC)* par des ingénieurs d'IBM. +
* *2011* : Warden
* *2013/02* : GRANDE ETAPE - ajout des *user namespaces* au kernel Linux 3.8
* *2013/03/20* : ETAPE MAJEURE - *1ere release de Docker* +
-> "Le monde découvre les containers"
* *2013/10* : LMCTFY
* *2014/02/20* : release de la 1ere version 1.0 de LXC
* *2014/06/07* : GRANDE ETAPE - toute première release de *Kubernetes* par Google (1er commit GitHub)
* *2014/11* : 1ere release de rkt (prononcer "rocket"), le container runtime créé par les équipes de CoreOS.
* *2015/06/17* : création de *WebAssembly*
* *2015/06* : GRANDE ETAPE - *Docker Inc donne la codebase du projet Docker à l'OCI*, projet de la Linux Fondation, *créé pour cette occasion*.
* *2015/07* : GRANDE ETAPE - *runc* est publié pour la 1ere fois, et son code a *tout de suite donné par Docker à l'OCI* (runc est l'implémentation de référence de la runtime-spec)
* *2015/07/21* : ETAPE MAJEURE - *release de la 1ere version de Kubernetes* par Google, et *création de la CNCF*, comme umbrella projet de la Linux Foundation, à laquelle Kubernetes sera donné comme élément fondateur.
* *2015/12* : GRANDE ETAPE - Docker introduce *containerd*
* *2016/03/14* : 1ere apparition des cgroups v2 dans le Linux Kernel 4.5
* *2016/04/13* : ETAPE MAJEURE - sortie de la *version 1.11 de Docker* : 1ere release de Docker basée sur containerd et runC (OCI) +
-> cette étape marque l'apparition des low-level et des high-level containers runtimes
* *2017/03/06* : GRANDE ETAPE - release de la v1.0 de WebAssembly 1.0 (MVP)
* *2017/03/15* : GRANDE ETAPE - *Docker's donation of containerd project to the CNCF*, and *CoreOS's donation of rkt to the CNCF*
* *2017/04* : Microsoft enabled organizations to run Linux containers on Windows Server.
* *2017/04/12* : apparition des "Distroless" container images chez Google
* *2017/07/19* : Release of the OCI v1.0 runtime and image specifications
* *2017/10* : DockerCon 2017, Docker announced they will support the Kubernetes container orchestrator, same thing for Azure and Amazon.
* *2018* : ETAPE MAJEURE - *L'avènement de Kubernetes*, où tous les Cloud providers propose leur offre de Kubernetes managé +
-> A partir de cette date, les containers deviennent présents partout, et dès lors, la *sécurité des containers* devient un sujet primordial.
    ** 2018 marque également l'apparition des "*sandbox runtimes*" : *Kata containers*, *gVisor*, *Nabla*
        *** *2018/05/02* : release initiale de *gVisor* par Google
        *** *2018/05/22* : lancement de la v1.0 de *Kata containers*
        *** *2018/07* : lancemnet des *Nabla containers*
    ** ainsi que celles des *daemonless runtimes* et du *rootless* : *podman* (avec *buildah* et *Skopeo*)
        *** *2018/04* : 1ere release de Podman
* *2019* : GRANDE ETAPE - les conséquences de l'essor de Kubernetes (le déclin de Docker et d'autres container runtimes)
* *2019/03/27* : ETAPE MAJEURE - 1st version de WASI (WebAssembly System Interface) qui marge l'essor de WebAssembly
* *2019/04* : la CNCF archive le projet rkt, suite à une adoption utilisateur en forte baisse
* *2019/11/12* : GRANDE ETAPE - *création de la Bytecode Alliance*, partenariat industriel poussant le développement de Wasm, tout particulièrement en dehors du browser (va marquer le début de l'essort rapide de WebAssembly)
* *2019/11/13* : Docker se scinde en 2 : Mirantis rachète Docker Enterprise, et Docker Inc se recentre autour de Docker Desktop (et Docker Hub) 
* *2020/02* : le project rkt est arrêté (https://github.com/rkt/rkt/issues/4024)
* *2020/12* : le daemon docker (dockerd) est déprécié pour Kubernetes 1.20 (2020/12), et est remplacé par containerd
* *2021* : les containers sont maintenant partout, et le constat suivent tiré des études de Gartner : +
"Gartner predicted in 2020 that, by 2022, more than 75% of global organisations will be running containerised applications in production, against 30% in 2020."
* *2021/05/05* : release de la v1.0.0 (version stable) de la distribution-spec de l'OCI (3e spécification de l'OCI)
* *2022/10/24* : ETAPE MAJEURE - Technical Preview de Docker, announces support for WebAssembly, in cooperation with WasmEdge, and joins the Bytecode Alliance as a voting member

