= Histoire de la conteneurisation : préparation de la prise de parole
Thomas SCHWENDER <icon:github[] https://github.com/Ardemius/[GitHub] / icon:twitter[role="aqua"] https://twitter.com/thomasschwender[@thomasschwender]>
// Handling GitHub admonition blocks icons
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:imagesdir: ./images
:resourcesdir: ./resources
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
// We must enable experimental attribute to display Keyboard, button, and menu macros
:experimental:
// Next 2 ones are to handle line breaks in some particular elements (list, footnotes, etc.)
:lb: pass:[<br> +]
:sb: pass:[<br>]
// check https://github.com/Ardemius/personal-wiki/wiki/AsciiDoctor-tips for tips on table of content in GitHub
:toc: macro
:toclevels: 4
// To number the sections of the table of contents
//:sectnums:
// Add an anchor with hyperlink before the section title
:sectanchors:
// To turn off figure caption labels and numbers
:figure-caption!:
// Same for examples
//:example-caption!:
// To turn off ALL captions
// :caption:

// toc::[]

== SLIDE : TITRE

Wahou, cela fait vraiment plaisir de voir que vous êtes aussi nombreux à avoir été intéressés par ce sujet 👍 
Quand j'ai vu le nombre de like sur l'application, je vous garantis que cela fait chaud au coeur.

== SLIDE : Je vous parle d'un temps que les moins de 20 ans, NON de 40 ans !, ne peuvent pas connaître

Donc bonjour à toutes et à tous,

Et bienvenue à ce talk où il va être question de *conteneurisation*, et plus particulièrement de *l'histoire et l'évolution de cette dernière depuis ses débuts*, il y a bieeennnnnnn longtemps, jusqu'à aujourd'hui.

== SLIDE : PRESENTATION

Alors, je me présente, je m'appelle Thomas SCHWENDER, je suis architecte au sein de la société *Softeam*, qui est depuis 2020 une entité du groupe *Docaposte*, qui lui-même appartient au groupe *La Poste* que tout le monde connaît bien. +
Les 2 sociétés ont cette année *un stand sur le salon*, n'hésitez pas à y faire un tour pour découvrir nos projets. On ne s'en doute peut-être pas de prime abord, mais de la *confiance numérique* à l'*eSanté* en passant par l'*IA*, on travaille vraiment sur des *enjeux de société très actuels*.

Depuis 2 ans, je mets également à jour un *article sur le blog de Devoxx France* qui explique *comment tirer profit au maximum de sa présence à un salon comme Devoxx*.
Entre autres conseils pratiques, j'y explique comment *créer sa propre base de connaissances* pour persister sa veille techno et la rendre facilement accessible et exploitable tout au long de sa carrière.

D'ailleurs, sur ce même thème, je vous conseille vraiment d'aller *assister vendredi à la conférence "Apprendre en continu avec sa veille technologique"* de Fabien Hiegel et David Franck.
Ils ont déjà donné ce talk au dernier DevFest Nantes, je l'ai trouvé top, et ils vont plus loin que moi sur ce concept de base de connaissance ou de "2nd cerveau" comme ils l'appellent.
Vraiment, pour vous, la veille que vous faites en salon, ou par d'autres moyens, faites en sorte qu'elle vous serve le plus longtemps possible, et qu'elle ne soit pas oubliée dans quelques jours ou semaines.

Sur ce revenons au *sujet qui va nous intéresser jusqu'à la fin du talk*, à savoir *comprendre par quoi l'informatique est passée* pour arriver jusqu'aux conteneurs tels qu'on les connaît aujourd'hui, et *pourquoi* ça s'est passé comme ça.
L'idée de ce talk est que, pour mieux comprendre le présent, et pouvoir envisager sereinement le futur, il est bon de connaître le passé et savoir d'où l'on vient.

-> C'est également l'idée d'une citation de Nicolas Machiavel (Philosophe (1469 - 1527)) : 
Pour prévoir l'avenir, il faut connaître le passé, car les événements de ce monde ont en tout temps des liens aux temps qui les ont précédés. Créés par les hommes animés des mêmes passions, ces événements doivent nécessairement avoir les mêmes résultats.

== SLIDE : DISCLAIMER

Petit disclaimer avant d'aller plus loin : on ne va *PAS expliquer comment se servir de Docker, Kubernetes ou WebAssembly* durant ce talk.
Le but est vraiment de se concentrer sur *l'enchaînement des progrès technologiques* au cours des années.

Autre point : n'allez surtout pas croire que je suis un spécialiste de chaque technologie présentée.
Il y aura donc des slides verbeux, car je ne suis tout simplement pas capable de tout retenir.

== SLIDE : PLAN

Donc en termes de plan, les choses sont simples : dans ce talk, il sera question de dates. +
Et dans l'histoire de la conteneurisation depuis les années 70s, des dates il y en a eu beaucoup... VRAIMENT beaucoup...

En fait, des dates, il y en a trop, on ne pourra pas entrer dans les détails de chacune, on va *se concentrer sur les plus importantes*.

PAR CONTRE, en *fin de talk*, je vous mettrai à disposition la *version complète de la chronologie* sur laquelle j'ai travaillé 😉 

== SLIDE : DEFINTION : CONTENEUR

Avant de débuter notre voyage dans le temps, il est important de revoir 2 concepts qui reviendront tout au long du talk.

Commençons par le 1er : mais au fait, *qu'est-ce donc qu'un conteneur ?*
Aussi surprenant que cela puisse paraître, il n'y a pas de réelle définition "officielle" de ce qu'est un "container"

Mais ce sur quoi tout le monde s'accorde est qu'à minima un conteneur est un *groupe de process isolés du reste du système (du host) par certains moyens techniques*.
Dans la suite du talk, nous allons justement préciser de quels moyens il est question.

== SLIDE : DEFINTION : RUNTIME

L'autre concept dont il est question est celui de *runtime*, ou environnement d'exécution.

Alors, runtime, runtime environment, RTE, environnement d'exécution, toutes ces expressions sont *synonymes*.

Et la définition que l'on peut en donner est qu'un runtime est la pile logicielle offrant les services nécessaires à l'exécution d'applications, et *UNIQUEMENT l’exécution*, PAS la compilation, et cela, *indépendamment du système d'exploitation*.

Le runtime met à disposition un certain nombre de fonctions de base au service de la *mémoire*, du *réseau* ou du *matériel* ET *exécute ces fonctions à la place de l’application*, indépendamment du système d’exploitation. C'est en fait le runtime qui fait donc le lien entre l’application et le système d’exploitation.

== SLIDE - RUNTIME : JRE vs JDK vs JVM

Un exemple bien connu de runtime est tout simplement le *JRE de Java*. +
Ce dernier englobe la *JVM* et la *JCL*, la *Java Class Library*, un ensemble de classes procurant à la JVM tout ce dont elle a besoin pour exécuter une application Java d'un point de vue *mémoire*, *réseau*, système de *fichiers*, spécificités *matérielles*.

On peut également donner d'autres exemples : 

* *Node.js* : qui est un environnement d'exécution permettant d'exécuter du *code Javascript* côté serveur.
* On y pense moins, mais il y a également le bon vieux *Cygwin* qui est un environnement d’exécution permettant aux *applications Linux* de fonctionner sur d'autres OS comme Windows ou macOS.

== SLIDE - RUNTIME : comparaison JRE vs Node.js

D'ailleurs si on compare le JRE à Node.js, on voit tout de suite les similitudes : 

    * En lieu et place de la JVM, Node.js utilise *V8*, le *moteur Javascript de Google*, initialement développé pour Chrome.
    * Et les classes de la JCL sont remplacées par des *modules équivalents* côté Node.js

== SLIDE 9 - 1970s

Bon, nous sommes maintenant parés pour notre voyage dans le temps, et pour débuter ce dernier, nous allons remonter jusqu'aux années 1970 !

== SLIDE - 1972

* L’idée originale de conteneur a germé dans les années 70s sur les systèmes *Unix*, lorsqu'on a eu besoin de mieux *isoler le code applicatif*.
    
* A cette époque les *ordinateurs* étaient très *chers* et donc très *rares*, aussi fallait-il pouvoir *les exploiter au maximum*. +
On a donc cherché à *partager leurs ressources entre différents utilisateurs*, sans que le travail de l'un n'ait d'impact sur celui de l'autre.
    
* L'autre problématique concernait *les tests*. On l'a dit les ordinateurs étaient très chers, on ne disposait donc souvent que d'*une seule machine* qui devait faire tourner ET les *systèmes de production* ET permettre aux développeurs de *tester leurs applications*. +
Il fallait donc que ces tests puissent se faire sans impacter les traitements de PROD, aussi c'est à cette époque que sont apparus *les 1eres "sandboxes"*, des environnements isolés permettant de tester applications, services et process ; en d'autres termes : les 1ers conteneurs.

Concernant la photo, il s'agit de *Ken Thompson* et *Dennis Ritchie* à côté d'un PDP-11 chez Bell Labs, vers 1972. +
Pour rappel, ce sont vraiment 2 des plus grands pionniers de l'informatique ; les créateurs d'Unix et du langage C. +
Ken Thompson est également le créateur du premier shell Unix en 1971, sur la 1ere version d'Unix. +

Personnellement, c'est une photo qui me touche, c'est l'alter ego informatique de "Trois hommes dans un salon" avec Brel, Brassens et Ferré en 1969, c'est un moment d'histoire...

== SlIDE - 1979 chroot

Dans cet exemple, "ls" ne peut pas accéder au répertoire racine initial, il est restreint à l'environnement isolé qu'on lui a donné.

Attention, chroot a plusieurs *problèmes de sécurité* connus. +
En l'occurrence, il est *facile de "s'échapper de l'environnement isolé"*

Raison pour laquelle les outils de conteneurisation actuels, comme Docker, utilisent à la place *pivot_root* pour lequel s'est bien moins facile.

== SLIDE - 2000s

Et là, gros gap, on va directement sauter aux années 2000, où vont apparaître les 1eres réelles implémentations d'outils de conteneurisation.

== SLIDE - FreeBSD Jails

== SLIDE - Linux VServer

Impossible de trouver un schéma d'architecture global de Linux VServer.
J'ai donc mis le schéma d'architecture du VServer Control Daemon, mais cela n'apporte vraiment rien dans notre cas.

Ce projet permet d'*exécuter une ou plusieurs distributions sur une distribution* (distribution = système d'exploitation sans le noyau)

Patcher le kernel Linux : une *charge en plus* pour les distributeurs et les sysadmin.

== SLIDE - 2002 - 1er LINUX NAMESPACE

== SLIDE - Julia EVANS "HOW TO MAKE A NAMESPACE"

J'en reparlerai en fin de talk, mais voici une planche créée par Julia EVANS pour vulgariser la création d'un namespace.
Je voulais vous la montrer car je trouve cela super bien fait, mais on ne va pas tout regarder.
Jetez juste un oeil au nom de la commande (unshare) permettant la création d'un namespace : "tu ne partageras point"

== SLIDE - 2002 - MOUNT NAMESPACES

Les mount namespaces sont utilisés pour isoler les points de montage du système de fichiers entre les différents processus, ce qui permet à chaque processus de disposer de son propre point de montage racine. Cela permet d'isoler les systèmes de fichiers et les processus entre eux, ce qui est essentiel pour la conteneurisation.

== SLIDE - 2003 - BORG 

Borg est bien toujours utilisé aujourd'hui (2022) dans les datacenters de Google, et PAS Kubernetes, qui est utilisé pour des services Cloud et est surtout destiné à des utilisateurs externes.

== SLIDE - 2004 - Solaris Containers (Zones Solaris)

== SLIDE - 2005 - OpenVZ

https://www.youtube.com/watch?v=sK5i-N34im8[cgroups, namespaces, and beyond: what are containers made from?] de Jérôme PETAZZONI

Container runtimes qui ne sont PAS basés sur les namespaces et les cgroups (fonctionnalités du noyau Linux) : 

    * *Jails*
    * *Solaris Containers*
    * *OpenVZ* 

-> Logique, ces 3 OS, même s'ils sont de type Unix, utilisent des noyaux différents, et les namespaces et les cgroups sont des fonctionnalités du noyau LINUX.

== SLIDE - Warden

Cloud Foundry a plus tard remplacé les Containers Linux par leur propre implémentation, utilisant toujours les cgroups et les namespaces

Le plus important pour Warden était de rendre possible la gestion d’environnements isolés par un moyen simple : une API.

== SLIDE cgroups + namespaces -> création de conteneurs

    * *pivot_root* : set a process's root directory to a directory with the contents of the container image
        ** difference between pivot_root and *chroot* : chroot is easy to escape from if you're root and pivot root isn't +
        -> so containers use pivot_root instead of chroot
        ** l'héritier de chroot en version plus sécurisée
    * *cgroups* : limit memory / CPU usage for a group of processes
        ** limiter COMBIEN on peut utiliser (mémoire, CPU)
    * *namespaces* : allow processes to have their own network / PIDs / users / hostname / mounts / and more !
        ** limiter ce que l'on peut voir

    * *seccomp-bpf* : security: prevent dangerous system calls
        ** seccomp means "secure computing"
        ** bpf, pour Berkeley Packet Filter, est une extension de seccomp
        ** vise à éviter les appels système dangereux

    * *capabilities* : security: avoid giving root access
        ** évite de donner les droits root
        ** Capabilities allow to reduce the privileges of an active process

Rappel : *System call* : a request for the operating system to do something on behalf of the user's program. The system calls are functions used in the kernel itself. +
Un appel système permet au programme utilisateur d'accéder aux fonctionnalités du noyau telles que la gestion des fichiers, des processus et des périphériques.

== SLIDE exemple de Julia Evans de création de conteneur à la main



== SLIDE - DOCKER 1ere release

* Libcontainer était une bibliothèque open source développée par Docker pour fournir une interface standardisée pour les fonctionnalités de conteneurisation du noyau Linux.
* Libcontainer a permis à Docker de devenir indépendant de la bibliothèque LXC et de fournir une interface *plus flexible* et plus sûre pour la *création*, la *gestion* et l'*orchestration* de conteneurs.
* *libcontainer* a été la base de *runc*, son ancêtre (runc tout de suite donné à l'OCI à sa création)

* *LXC* (Linux Containers) : easy for sysadmins / OPS, hard for devs (requires significant elbow grease)
* Solomon : on avait déjà les Linux Containers (LXC) avant, mais ce type de Operating System (OS) Containers n'est pas des plus simples à utiliser. Ces derniers sont plutôt à destination des sysadmin, pas des équipes qui "ship"

== SLIDE - RAISON D'ETRE DOCKER, POURQUOI ?

* Donc, pour résumer, on a fait Docker dans le but de *shipper*. +
Il fallait donc que Docker ne soit pas "trop infâme" à utiliser.
    ** on avait déjà les Linux Containers (LXC) avant, mais ce type de Operating System (OS) Containers n'est pas des plus simples à utiliser. Ces derniers sont plutôt à destination des sysadmin, pas des équipes qui "ship"

* Que faisait Dotcloud à la base ?

== SLIDE - PROBLEME DE SECURITE

* "*Concern and hesitation* arose in the IT community regarding the *security of a shared OS kernel*" (https://searchitoperations.techtarget.com/feature/Dive-into-the-decades-long-history-of-container-technology)

* parler du grand problème de Docker, le "monolith daemon that required root access for everything" +
Ce qui a conduit à l'émergence des daemonless et autre rootless comme Podman et Buildah

* https://www.techtarget.com/searchitoperations/feature/Dive-into-the-decades-long-history-of-container-technology +
"Sysdig's "2022 Cloud-Native Security and Usage Report" found that 75% of respondents were running containers with high or critical vulnerabilities, and *76% had containers running as root*, playing a dangerous game with IT ecosystem safety."
    ** une partie des résultats de l'étude est disponible ici : https://sysdig.com/blog/2022-cloud-native-security-usage-report/
        *** chercher Container Security le chiffre de 76% précédent qui nous intéresse

== SLIDE DOCKER ROOT PLEASE !

Y a-t-il des OPS dans la salle ?
Y a-t-il des OPS qui ont vécu l'arrivée de Docker vers 2013 à 2015 ?
Si oui, pardon... Souvenir douloureux...

DOCKER ROOT PLEASE ! (2015)

* notes de Daniel sur l'exploit : https://github.com/VonC/blog/blob/201711_docker/PITCHME.md
* Explication de l'exploit : https://fosterelli.co/privilege-escalation-via-docker (2015/04/22)

* https://sysdig.com/blog/2022-cloud-native-security-usage-report/ : pour les 76% de containers en root toujours en 2022


== SLIDE WASM

* Au final : donner l'exemple de Wordpress qui tourne dans le browser : https://wordpress.wasmlabs.dev/

== SLIDE XXX - RESSOURCES et REMERCIEMENTS

Un immense merci à tous les auteur(e)s des articles de blog, ebooks et vidéos que j'ai lus et vues pour préparer ce sujet. +

J'ai consulté des dizaines et des dizaines de publications, je ne peux pas nommer toutes les personnes à remercier, mais je vous garantis que le coeur y est.

Remerciements particuliers à *Julia Evans* (@b0rk), dont je trouve le travail fantastique 👍 
Pour celles et ceux qui ne la connaissent pas, Julia vulgarise des concepts compliqués en BD.
C'est concis et limpide, je ne saurais que trop vous conseiller d'aller jeter un oeil à son travail.
Elle publie régulièrement sur Twitter et pour la soutenir vous pouvez également acheter ses "zines" pour quelques euros sur son site https://wizardzines.com/
(Et dans le cas de ce talk, tout particulièrement le zine *"How containers work"*)

== SLIDE FIN

Voilà, notre voyage dans le temps est terminé.

Je vous remercie et j'espère que vous avez pu découvrir des choses que vous ne saviez pas sur l'histoire de la conteneurisation depuis ses lointains débuts jusqu'à aujourd'hui.
